### ISSUE TITLE
Anonymous Blocks and package body fails

### ISSUE THREAD

**Issue by dados** [KonnexionsGmbH/plsql_parser#1]
Hi,

This first one is similar to your test and it works. 
But the other two below fail. One is the package body part of the first and the other is a simple anonymous block

{ok, {ParseTree, Tokens}} = plsql_parser:parsetree_with_tokens("
CREATE OR REPLACE PACKAGE my_package
IS
  FUNCTION MY_FUNCTION RETURN BOOLEAN;
END my_package;
").

/

{ok, {ParseTree, Tokens}} = plsql_parser:parsetree_with_tokens("
CREATE OR REPLACE PACKAGE BODY my_package
IS
  FUNCTION MY_FUNCTION
  RETURN BOOLEAN
  IS
  BEGIN
      IF 1 = 2 THEN
        RETURN FALSE;
      ELSE
        RETURN TRUE;
      END IF;
  END;
END my_package;
").

/

{ok, {ParseTree, Tokens}} = plsql_parser:parsetree_with_tokens("
declare
  l_num number;
begin
  l_num := 10;
end;
").

**Comment by walter-weinmann** [comment]
This is both valid PL/SQL on the one hand a `plsql_block` and on the other hand a `create_package_body`, but unfortunately both language constructions are not supported in plsql_parser, see here: https://github.com/KonnexionsGmbH/plsql_parser/wiki/Syntax-Diagram.
